### ISSUE TITLE
undefined: termui.PollEvent

### ISSUE THREAD

**Issue by utkarsh2102** [gizak/termui#203]
I am trying to build `termui` on Debian and getting the following error:
```
src/github.com/gizak/termui/test/log_events.go:23:10: undefined: termui.PollEvent

dh_auto_build: cd obj-x86_64-linux-gnu && go install -gcflags=all=\"-trimpath=/home/utkarsh2102/packaging/something/termui/obj-x86_64-linux-gnu/src\" -asmflags=all=\"-trimpath=/home/utkarsh2102/packaging/something/termui/obj-x86_64-linux-gnu/src\" -v -p 4 github.com/gizak/termui github.com/gizak/termui/test returned exit code 2
make: *** [debian/rules:7: build] Error 2
```

**Comment by cjbassi** [comment]
Should be good now, thanks for pointing it out.

**Comment by utkarsh2102** [comment]
Great, thanks for resolving! :D
Although, there's another build failure, mentioned in #204.
